version: "3.8"
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    networks:
      - edb
  electro:
    image: node:18-alpine
    environment:
      LOCAL_DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: "tail -f /dev/null"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - edb
networks:
  edb:
    driver: "bridge"
